@API_HostAddress = https://localhost:7230

GET {{API_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{API_HostAddress}}/api/machine

###

POST {{API_HostAddress}}/api/machine
Content-Type: application/json

{
  //CreateMachineDto
}

###

GET {{API_HostAddress}}/api/machine/0

###

DELETE {{API_HostAddress}}/api/machine/0

###

PUT {{API_HostAddress}}/api/machine/0
Content-Type: application/json

{
  //UpdateMachineDto
}

###
